version: "3.7"
services:
  app_be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    environment:
      - MYSQL_USER=user123
      - MYSQL_PASS=2022Mysql!!
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - DB_NAME=news_app
    depends_on:
      - mysql
    networks:
      - web

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=XmQrkvWyCXkrzq7
      - MYSQL_DATABASE=news_app
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=2022Mysql!!
    networks:
      - web

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  dbdata: